import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Multiplayer = ({ room }: MultiplayerInterface) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PokeMemory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Multiplayer {room}</h1>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const room = context.query['room']

  return {
    props: {
      room,
    }, // will be passed to the page component as props
  }
}

interface MultiplayerInterface {
  room: string
}

export default Multiplayer
